<a href="https://colab.research.google.com/github/alfmorais/estrutura_de_dados_em_python/blob/main/secao_6/aula_75.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Filas (First In First Out)
#Aula 71


*   A primeira pessoa a entrar no final da fila será a primeira pessoa a chegar na frente da fila.
*   É uma estrutura semelhante a uma pilha, exceto que em uma fila o primerio elemento inserido é o primeiro a ser removido (First In First Out - Primeiro a entrar Primeiro a sair). 
*   Aplicações
> *   Modelar aviões aguardando para decolar
> *   Pacotes de dados esperando para serem transmitidos pela rede
> *   Fila da impressora, no qual serviços de impressão aguardam a impressora ficar disponível. 
> *   Armazena os dados digitados pelo teclado em um processador de texto. 

##Operações



*   Enfilerar: colocar um item no final da fila
*   Desenfileirar: remover um item do inicio da fila
*   Ver início da fila: monstra o elemento que está no início da fila

##Fila circular
Os elementos circulam dentro do vetor. 











In [1]:
import numpy as np

In [2]:
class Fila_Circular:

  def __init__(self, capacidade):
    self.capacidade = capacidade
    self.inicio = 0
    self.final = -1
    self.numero_elementos = 0
    self.valores = np.empty(self.capacidade, dtype=int)

  def __fila_vazia(self):
    return self.numero_elementos == 0

  def __fila_cheia(self):
    return self.numero_elementos == self.capacidade

  def enfileirar(self, valor):
    if self.__fila_cheia():
      print('A fila está cheia')
      return

    if self.final == self.capacidade - 1:
      self.final = -1
    self.final += 1
    self.valores[self.final] = valor
    self.numero_elementos += 1

  def desenfileirar(self):
    if self.__fila_vazia():
      print('A fila já está vazia')
      return

    temp = self.valores[self.inicio]
    self.inicio += 1
    if self.inicio == self.capacidade:
      self.inicio = 0
    
    self.numero_elementos -= 1
    return temp
  
  def primeiro(self):
    if self.__fila_vazia():
      return -1
    return self.valores[self.inicio]

In [3]:
fila = Fila_Circular(5)

In [4]:
fila.primeiro()

-1

In [5]:
fila.enfileirar(1)

In [6]:
fila.enfileirar(2)
fila.enfileirar(3)
fila.enfileirar(4)

In [7]:
fila.primeiro()

1

In [8]:
fila.enfileirar(5)

In [9]:
fila.enfileirar(6)

A fila está cheia


In [10]:
fila.desenfileirar()
fila.desenfileirar()

2

In [11]:
fila.primeiro()

3

In [12]:
fila.enfileirar(6)
fila.enfileirar(7)

In [13]:
fila.primeiro()

3

In [14]:
fila.valores

array([6, 7, 3, 4, 5])

In [20]:
fila.inicio, fila.final
print('Posição inicial da fila: ', fila.inicio, 'Valor do Array: ', fila.valores[fila.inicio])
print('Posição final da fila: ', fila.final, 'Valor do Array: ', fila.valores[fila.final])

Posição inicial da fila:  2 Valor do Array:  3
Posição final da fila:  1 Valor do Array:  7


In [16]:
fila.valores[fila.final]

7

# Filas de Prioridade

- Os itens são ordenados por valor-chave, de modo que o item com a chave mais baixa/alta esteja sempre na frente.
- Elementos de alta prioridade são colocados no início da fila, de média prioridade no meio da fila e elementos de baixa prioridade no final da fila. 
- Priority Queue
- Array Simples
- Vetor Circular
- Vetor

In [ ]:
import numpy as np

In [22]:
class Fila_Prioridade:
  def __init__(self, capacidade):
    self.capacidade = capacidade
    self.numero_elementos = 0
    self.valores = np.empty(self.capacidade, dtype=int)

  def __fila_vazia(self):
    return self.numero_elementos == 0
    
  def __fila_cheia(self):
    return self.numero_elementos == self.capacidade

  def enfileirar(self, valor):
    if self.__fila_cheia():
      print('A fila está cheia')
      return

    if self.numero_elementos == 0:
      self.valores[self.numero_elementos] = valor
      self.numero_elementos += 1
    else:
      # 7 6 5
      x = self.numero_elementos - 1
      while x >= 0:
        if valor > self.valores[x]:
          self.valores[x + 1] = self.valores[x]
        else:
          break
        x -= 1
      self.valores[x + 1] = valor
      self.numero_elementos += 1

  def desenfileirar(self):
    if self.__fila_vazia():
      print('A fila está vazia')
      return

    valor = self.valores[self.numero_elementos - 1]
    self.numero_elementos -= 1
    return valor

  def primeiro(self):
    if self.__fila_vazia():
      return -1
    return self.valores[self.numero_elementos - 1]

In [23]:
fila = Fila_Prioridade(5)

In [24]:
fila.primeiro()

-1

In [25]:
fila.enfileirar(30)

In [26]:
fila.primeiro()

30

In [27]:
fila.enfileirar(50)

In [28]:
fila.enfileirar(10)

In [29]:
fila.primeiro()

10

In [30]:
fila.valores

array([50, 30, 10,  0,  0])

In [31]:
fila.enfileirar(1)

In [32]:
fila.enfileirar(2)

In [33]:
fila.valores

array([50, 30, 10,  2,  1])

In [38]:
fila.desenfileirar()
fila.desenfileirar()
fila.desenfileirar()
fila.valores

A fila está vazia
A fila está vazia
A fila está vazia


array([50, 30, 10,  2,  1])

In [37]:
fila.valores

array([50, 30, 10,  2,  1])